### ISSUE TITLE
(progress #:range) contract

### ISSUE THREAD

**Issue by benknoble** [Bogdanp/racket-gui-easy#16]
The contract for `progress`'s `#:range` is documented as `(maybe-obs gui:dimension-integer?)` which should be equivalent to `(maybe-obs (integer-in 0 1000000))`.

However:
```scheme
(render (window (progress 0 #:range 0)))
```
gives the following, which references `positive-dimension-integer?` in the `#:range` argument
```
progress: contract violation
  expected: positive-dimension-integer?
  given: 0
  in: a part of the or/c of
      the #:range argument of
      (->*
       ((or/c
         position-integer?
         (obs/c position-integer?)))
       (#:enabled?
        (or/c boolean? (obs/c boolean?))
        #:label
        (or/c label-string? (obs/c label-string?))
        #:min-size
        (or/c
         (list/c
          (or/c #f dimension-integer?)
          (or/c #f dimension-integer?))
         (obs/c
          (list/c
           (or/c #f dimension-integer?)
           (or/c #f dimension-integer?))))
        #:range
        (or/c
         positive-dimension-integer?
         (obs/c positive-dimension-integer?))
        #:stretch
        (or/c
         (list/c boolean? boolean?)
         (obs/c (list/c boolean? boolean?)))
        #:style
        (listof
         (or/c
          'horizontal
          'vertical
          'plain
          'vertical-label
          'horizontal-label
          'deleted)))
       (is-a?/c view<%>))
  contract from:
      <pkgs>/gui-easy-lib/gui/easy/view.rkt
  blaming: top-level
   (assuming the contract is correct)
  at: <pkgs>/gui-easy-lib/gui/easy/view.rkt:145:3
```

P.S. Hopefully you are taking these reports as signs of an enthusiastic user rather than gripes and complaints. As I play with things, often in the setting of a personal but real project, I run into questions or concerns. I plan to keep playing, because gui-easy is far more ergonomic for me than racket/gui ❤️

**Comment by Bogdanp** [comment]
Thanks for the report! The docs were wrong in this case.  

> P.S. Hopefully you are taking these reports as signs of an enthusiastic user rather than gripes and complaints. As I play with things, often in the setting of a personal but real project, I run into questions or concerns. I plan to keep playing, because gui-easy is far more ergonomic for me than racket/gui ❤️

Absolutely! These are helpful so please keep them coming as you encounter them. I don't mind at all.
