### ISSUE TITLE
tabs: 'new-button (send tab-panel on-new-request) not implemented

### ISSUE THREAD

**Issue by benknoble** [Bogdanp/racket-gui-easy#19]
https://github.com/Bogdanp/racket-gui-easy/blob/831be1d3c466a0f6fe0e2e382be6fe801d81a936/gui-easy/gui/easy/scribblings/reference.scrbl#L190

The documentation mentions `'new-button`, but the implementation does not yet support it. Fortunately I can add it to my application in other ways, so perhaps a quick update to the doc is all that is needed?

**Comment by Bogdanp** [comment]
Whoops, I closed this prematurely. I've changed the contract to allow `'new-button`, but need to implement the hook still.

**Comment by Bogdanp** [comment]
OK, I've now pushed a change to handle the new button event. The `action` on tabs can now receive `'new` events as well.
