### ISSUE TITLE
Documentation for case-view condition doesn't match implementation

### ISSUE THREAD

**Issue by cloudrac3r** [Bogdanp/racket-gui-easy#29]
`case-view` documentation says that it uses `equal?` to compare the observable against the lit, but the implementation uses `memv` which is the `eqv?` condition. This makes it impossible to switch on strings because they can't be compared by `eqv?`.

Suggested solution: Change `case-view`'s implementation to use `member` as the test.

Relevant code: `private/view/if.rkt` line 137.

As always, thank you for your amazing work!

**Comment by Bogdanp** [comment]
Thanks!
