### ISSUE TITLE
Default keymap for (input) should be (keymap:get-editor)

### ISSUE THREAD

**Issue by cloudrac3r** [Bogdanp/racket-gui-easy#30]
The current default is to have no keybinds, but I don't think this is very helpful. We all expect Ctrl+C/Ctrl+V et al to be available everywhere!

[(keymap:get-editor)](https://docs.racket-lang.org/framework/Keymap.html#%28def._%28%28lib._framework%2Fmain..rkt%29._keymap~3aget-editor%29%29) includes all the keybinds that I would expect for a plain text field and it makes sense as a default.

This would save me a couple lines of code and memorisation each time I make a little application with gui-easy :)

**Comment by Bogdanp** [comment]
This used to be the default, but I dropped it because `framework` takes a couple seconds to load, so it was annoying when writing small tools. I agree that not having those keybindings is also annoying in its own right, though. Would you be willing to add some of the basic keybindings for your platform to "gui/easy/private/view/keymap.rkt"? If not, I can probably take care of it later this week.

**Comment by cloudrac3r** [comment]
Oh, that's interesting. I've never personally noticed that `framework` takes additional time to load, but I believe you.

> Would you be willing to add some of the basic keybindings for your platform to "gui/easy/private/view/keymap.rkt"?

I can test on Linux and Windows. I'll take a look and see what I can do!

**Comment by cloudrac3r** [comment]
I came up with this for my Linux computer:

```
(case (system-type 'os)
  [(macosx)
   (add&map "c:a" 'goto-start (λ (editor _event)
                                (send editor set-position 0)))
   (add&map "c:e" 'goto-end (λ (editor _event)
                              (send editor set-position (send editor last-position))))
   (add&map "d:a" 'select-all (λ (editor _event)
                                (send editor do-edit-operation 'select-all)))]
  [(unix)
   (add&map ":c:a" 'select-all (λ (editor _event)
                                (send editor do-edit-operation 'select-all)))
   (add&map ":c:z" 'undo (λ (editor _event)
                          (send editor do-edit-operation 'undo)))
   (add&map ":c:Z" 'redo (λ (editor _event)
                            (send editor do-edit-operation 'redo)))
   (add&map ":c:x" 'cut (λ (editor _event)
                         (send editor do-edit-operation 'cut)))
   (add&map ":c:c" 'copy (λ (editor _event)
                          (send editor do-edit-operation 'copy)))
   (add&map ":c:v" 'paste (λ (editor _event)
                           (send editor do-edit-operation 'paste)))])
```

However, undo and redo don't seem to fully work. I think the keybinds are activating but the editor is not recording the undo/redo history correctly, and I need to go to bed rather than debugging this right now. It would also be a nice-to-have if Ctrl+Left, Ctrl+Right, Alt+Left, Alt+Right moved the cursor backward and forward one word, which there doesn't seem to be a built in method for. At least cut/copy/paste all work.

**Comment by Bogdanp** [comment]
I've pushed another update to support moving backward and forward by word. I think that covers the basics, but do let me know if one of the Windows/Linux bindings is wrong or if there are others we should add.

**Comment by cloudrac3r** [comment]
Works great on Windows, great job :)
