### ISSUE TITLE
`group` does not accept styles shown in docs

### ISSUE THREAD

**Issue by otherjoel** [Bogdanp/racket-gui-easy#31]
The docs say that [`group`](https://docs.racket-lang.org/gui-easy/index.html#%28def._%28%28lib._racket%2Fgui%2Feasy..rkt%29._group%29%29) accepts these values in the `#:style` argument:

```racket
(listof (or/c 'border 'deleted
              'hscroll 'auto-hscroll 'hide-hscroll
              'vscroll 'auto-vscroll 'hide-vscroll))
```

…but of these, only `'deleted` is actually accepted. Using any of the other values results in:

```
initialization for group-box-panel%: invalid symbol in given style list
  invalid symbol: 'border
  given: '(border)
```

This makes sense, given that the underlying [`group-box-panel%`](https://docs.racket-lang.org/gui/group-box-panel_.html#%28constructor._%28%28lib._mred%2Fmain..rkt%29._group-box-panel~25%29%29) also only accepts `'deleted` for its style argument.

**Comment by Bogdanp** [comment]
Thanks! I've pushed a doc fix.
