### ISSUE TITLE
dialog with `close-button` style has no close button

### ISSUE THREAD

**Issue by otherjoel** [Bogdanp/racket-gui-easy#45]
Not sure if this is expected or what. The program in `examples/modal.rkt` sets the `#:style` of its dialog to `'(close-button)`, but running it and clicking the button to render a dialog produces a dialog with no close button:

<img width="247" alt="image" src="https://github.com/Bogdanp/racket-gui-easy/assets/1553115/b7fb91f8-a13f-47a9-8d4f-e02274232cb6">

The only way to close the dialog is to press ESC.

**Comment by Bogdanp** [comment]
This is expected, though maybe the example should be updated. When run on its own, the dialog will have a close button, but when run as a modal dialog, it's displayed as a sheet on macOS so the close button style has no effect.
