### ISSUE TITLE
Documentation suggestions: list-view

### ISSUE THREAD

**Issue by kengruven** [Bogdanp/racket-gui-easy#53]
`list-view` documentation is a bit ambiguous in a couple places, which I had to figure out by trial-and-error or reading the source code:

- `make-view` has type `(-> any/c any/c (is-a?/c view<%>))`.  Below this, it says it "renders the entries by passing each one as a derived observable to make-view".  Later in an example it says "The list-view renders each individual counter by passing in a derived observable to its make-view argument.
  - That sounds to me like it takes 1 argument, when it actually takes 2 arguments: the key, and the entry (wrapped in an observable).
- `key` has type `(-> any/c any/c)`.  The documentation only says "Each entry must have a unique #:key."
  - What it means is that key is a function that takes one of `entries` as input, and returns a value which will be used as a key in `make-hash` for this `list-view`, i.e., it's compared using `equal?`, and it only has to be unique within this `list-view`.

Maybe it's just me, but these details were not obvious to me.

**Comment by Bogdanp** [comment]
Thanks for the suggestion! I've pushed an update, but let me know if it's still unclear. Doc (and other) PRs are always welcome so feel free to make your own edits if you feel something could be explained better.

**Comment by kengruven** [comment]
I think what you wrote looks great.  Thank you!
